server:
  host: "0.0.0.0"
  port: 50051
  max_concurrent_streams: 100

subpub:
  buffer_size: 100
  drop_strategy: "newest"  # none, oldest, newest
  worker_pool_size: 10

log:
  level: "debug"       # debug, info, warn, error
  format: "json"      # json, console
